export const themes = {
  classic: {
    backgroundColor: '#FDFBF7',
    previewBg: '#FDFBF7',
    fontFamily: 'serif',
    textColor: '#374151',
    primaryColor: '#374151',
    accentColor: '#FBBF24',
    bg: 'bg-gradient-to-br from-amber-50 via-white to-gray-50',
    header: 'bg-white border-b-2 border-gray-200',
    card: 'bg-white border-2 border-gray-200 rounded-lg',
    title: 'font-serif text-2xl font-bold text-gray-800',
    subtitle: 'font-serif text-gray-600',
    text: 'text-gray-700',
    button: 'px-5 py-2.5 bg-gray-800 text-white rounded-md hover:bg-gray-900 transition-colors font-serif',
    input: 'border-2 border-gray-300 rounded-md focus:border-gray-800 focus:ring-0',
    messageMyBg: 'bg-amber-100 border border-amber-200',
    messageTheirBg: 'bg-gray-100 border border-gray-200',
    messageMySender: 'text-amber-800',
    messageTheirSender: 'text-gray-500',
  },
  modern: {
    backgroundColor: '#f5f5f7',
    previewBg: '#f5f5f7',
    fontFamily: 'sans-serif',
    textColor: '#111827',
    primaryColor: '#3b82f6',
    accentColor: '#8B5CF6',
    bg: 'bg-[#f5f5f7]',
    header: 'bg-white/80 backdrop-blur-xl border-b border-white/30 shadow-lg',
    card: 'bg-white/70 backdrop-blur-xl rounded-2xl shadow-lg border border-white/30',
    title: 'text-3xl font-bold text-gray-900',
    subtitle: 'text-gray-600 font-medium',
    text: 'text-gray-700',
    button: 'px-6 py-3 bg-blue-500 text-white rounded-full hover:bg-blue-600 transition-all font-semibold shadow-md',
    input: 'bg-white/80 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all text-sm shadow-sm',
    messageMyBg: 'bg-gradient-to-br from-blue-500 to-blue-600 text-white',
    messageTheirBg: 'bg-white/80 border border-gray-200/50',
    messageMySender: 'text-white/80',
    messageTheirSender: 'text-gray-500',
  },
  minimalist: {
    backgroundColor: '#ffffff',
    previewBg: '#ffffff',
    fontFamily: 'sans-serif',
    textColor: '#000000',
    primaryColor: '#000000',
    accentColor: '#4B5563',
    bg: 'bg-white',
    header: 'bg-white border-b border-gray-300',
    card: 'bg-white border border-gray-300',
    title: 'text-2xl font-semibold text-black tracking-wide',
    subtitle: 'text-gray-700',
    text: 'text-gray-800',
    button: 'px-5 py-2.5 border-2 border-black text-black hover:bg-black hover:text-white transition-all',
    input: 'border border-gray-400 focus:border-black focus:ring-0',
    messageMyBg: 'bg-black text-white',
    messageTheirBg: 'bg-gray-200',
    messageMySender: 'text-gray-400',
    messageTheirSender: 'text-gray-500',
  },
  bold: {
    backgroundColor: '#000000',
    previewBg: '#000000',
    fontFamily: 'monospace',
    textColor: '#f3f4f6',
    primaryColor: '#facc15',
    accentColor: '#38BDF8',
    bg: 'bg-black',
    header: 'bg-black border-b-4 border-yellow-400',
    card: 'bg-gray-900 border-4 border-yellow-400',
    title: 'text-3xl font-black text-yellow-400 uppercase tracking-wider',
    subtitle: 'text-gray-400 font-mono uppercase',
    text: 'text-gray-300 font-mono',
    button: 'px-6 py-3 bg-yellow-400 text-black rounded-md hover:bg-cyan-400 transition-all font-black uppercase',
    input: 'bg-gray-800 border-2 border-yellow-400 text-white focus:border-cyan-400 focus:ring-0',
    messageMyBg: 'bg-yellow-400 text-black font-bold',
    messageTheirBg: 'bg-gray-800 text-white border-2 border-gray-700',
    messageMySender: 'text-black/70',
    messageTheirSender: 'text-gray-400',
  },
};